### PR TITLE
SSL support and receive delivery_tag

### PR DESCRIPTION
**Pull request by jbriggs-zvelo**
I found this code on CPAN and it was almost what I needed. I didn't want to compile C code so a Pure Perl module was perfect.

I had to add SSL support and fix the receive method since it wasn't quite working for me. I also did the server tuning frame max because it seemed like a good idea.

### CODE REVIEW

**Comment by leejo** [comment]
Hi! Seems OK but tests are now failing, could you look into those? Also could you remove the whitespace changes? I know we can ignore those in the diffs with a flag, but i dislike unnecessary churn in the history. Ta!

**Comment by jbriggs-zvelo** [comment]
I will fix the tests. It looks like delivery_tag was (and still is) being returned in method_frame. But of course I didn't know that at first and the documentation claims it is in the top-level object returned by receive. And my fixed way matches better with how basic_get works too, I think.

So the tests need to be fixed to expect a delivery_tag in the top level.

As for whitespace do you mean in the commit that adds IO::Socket::SSL or in the whitespace commit? 

I don't know if I can ethically continue to allow those abominations of mixed tabs and spaces to exist. :-)
I can work with spaces and I can work with tabs but mixing them is just not on.

**Comment by leejo** [comment]
OK great, thanks! Yes, i'd prefer to not have churn in the repo w/r/t whitespace changes - to me a clean history is more valuable than clean code, especially when i've taken over maintenance of a module from someone else. I can live with mixed tabs/spaces, it really doesn't bother me.

**Comment by leejo** [comment]
@jbriggs-zvelo - i've added a tweaked version of your patch for SSL support in f419b68. I haven't added the delivery tag, nor have I tweaked the frame max. If/when CI passes I will push this to CPAN. Thanks for the contribution!

**Pull request closed without merging**
